on:
  pull_request:
  push:
    branches: [add-arm-support]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker login --username "$DOCKER_USER" --password "$DOCKER_PASS" ghcr.io
      env:
        DOCKER_USER: ${{ github.actor }}
        DOCKER_PASS: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name != 'pull_request'
    - run: make build
